language: node_js
node_js:
  - "7"

branches:
  only:
  - master

before_install:
  - npm install -g firebase-tools

install:
  - cd functions && npm install

script:
  - firebase deploy --only functions --token "$FIREBASE_TOKEN"

notifications:
  email:
    on_failure: change
    on_success: change